name: Deploy Vantage FE to SSH Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      # Step 2: Install dependencies with --legacy-peer-deps
      - name: Install Dependencies
        run: |
          cp .env.local .env
          npm install --legacy-peer-deps

      - name: Build React.js
        run: |
          npm run build

      # Step 3: Transfer the build folder to server
      - name: Deploy to Server
        run: |
          sshpass -p '530EYuBe0rS7KY5@' rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
            ./ \
            root@147.93.30.80:/var/www/vl-web-fe/

      # Step 4: Set correct permissions (optional)
      - name: Set Permissions
        run: |
          sshpass -p '530EYuBe0rS7KY5@' ssh -o StrictHostKeyChecking=no root@147.93.30.80 '
            chmod -R 755 /var/www/vl-web-fe &&
            chown -R www-data:www-data /var/www/vl-web-fe
          '

      # Step 5: Restart Server (if necessary)
      - name: Restart Server (optional)
        run: |
          sshpass -p '530EYuBe0rS7KY5@' ssh -o StrictHostKeyChecking=no root@147.93.30.80 '
            systemctl restart nginx
          '
